//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIFramework.Examples {
    
    
    public sealed class ScreenIds {
        
        public const string ModeSelectionWindow = "ModeSelectionWindow";
        
        public const string PlayerHUDPanel = "PlayerHUDPanel";
        
        public const string PlayerReadyWindow = "PlayerReadyWindow";
        
        public const string Start = "Start";
    }
}
